#!/bin/bash

###
# Make sure this has execute permissions.
# eg, `chmod +x .git/hooks/pre-commit`

###
# Check if the tests even exist.
if [ ! -f "tests.py" ]; then
    echo "Can't find tests.py, aborting commit."
    exit 1
fi

###
# If you have any unstaged commits, just 
git stash -q --keep-index
python tests.py
RESULT=$?
git stash pop -q
[ $RESULT -ne 0 ] && exit 1
exit 0
